# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

version: 2
updates:
- package-ecosystem: maven
  directory: /
  schedule:
    interval: weekly
  ignore:
    # ignore any artifacts to comply with jgit version - those are managed manually!
    - dependency-name: "com.google.code.gson:*"
    - dependency-name: "org.apache.sshd:*"
    # ignore slf4j-api - will be managed manually
    - dependency-name: "org.slf4j:slf4j-api"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
